### ISSUE TITLE
Change names to raw data.

### ISSUE THREAD

**Issue by almamelisa** [almamelisa/Euphoniinae-Subfamily#2]
I want to change the name of the raw data to catalog number

**Comment by almamelisa** [comment]
#The goal of this script is change the original names of raw files to catalog number. 
#This script is in process


a=( 
1940_ATGCCGCT-AAGGAGTA_S880_L007_R1_001.fastq.gz 
1940_ATGCCGCT-ACTGCATA_S868_L007_R1_001.fastq.gz
1940_ATGCCGCT-AGAGTAGA_S844_L007_R1_001.fastq.gz
1940_ATGCCGCT-CTAAGCCT_S892_L007_R1_001.fastq.gz
1940_ATGCCGCT-CTCTCTAT_S820_L007_R1_001.fastq.gz
1940_ATGCCGCT-GTAAGGAG_S856_L007_R1_001.fastq.gz
1940_ATGCCGCT-TAGATCGC_S808_L007_R1_001.fastq.gz
1940_ATGCCGCT-TATCCTCT_S832_L007_R1_001.fastq.gz
1940_ATTCGTTG-AAGGAGTA_S875_L007_R1_001.fastq.gz
1940_ATTCGTTG-ACTGCATA_S863_L007_R1_001.fastq.gz
1940_ATTCGTTG-AGAGTAGA_S839_L007_R1_001.fastq.gz
1940_ATTCGTTG-CTAAGCCT_S887_L007_R1_001.fastq.gz
1940_ATTCGTTG-CTCTCTAT_S815_L007_R1_001.fastq.gz
1940_ATTCGTTG-GTAAGGAG_S851_L007_R1_001.fastq.gz
1940_ATTCGTTG-TAGATCGC_S803_L007_R1_001.fastq.gz
1940_ATTCGTTG-TATCCTCT_S827_L007_R1_001.fastq.gz
1940_CAAGTGTC-AAGGAGTA_S881_L007_R1_001.fastq.gz
1940_CAAGTGTC-ACTGCATA_S869_L007_R1_001.fastq.gz
1940_CAAGTGTC-AGAGTAGA_S845_L007_R1_001.fastq.gz
1940_CAAGTGTC-CTAAGCCT_S893_L007_R1_001.fastq.gz
1940_CAAGTGTC-CTCTCTAT_S821_L007_R1_001.fastq.gz
1940_CAAGTGTC-GTAAGGAG_S857_L007_R1_001.fastq.gz
1940_CAAGTGTC-TAGATCGC_S809_L007_R1_001.fastq.gz
1940_CAAGTGTC-TATCCTCT_S833_L007_R1_001.fastq.gz
1940_CCAAGCGA-AAGGAGTA_S878_L007_R1_001.fastq.gz
1940_CCAAGCGA-ACTGCATA_S866_L007_R1_001.fastq.gz
1940_CCAAGCGA-AGAGTAGA_S842_L007_R1_001.fastq.gz
1940_CCAAGCGA-CTAAGCCT_S890_L007_R1_001.fastq.gz
1940_CCAAGCGA-CTCTCTAT_S818_L007_R1_001.fastq.gz
1940_CCAAGCGA-GTAAGGAG_S854_L007_R1_001.fastq.gz
1940_CCAAGCGA-TAGATCGC_S806_L007_R1_001.fastq.gz
1940_CCAAGCGA-TATCCTCT_S830_L007_R1_001.fastq.gz
1940_CCATATGT-AAGGAGTA_S876_L007_R1_001.fastq.gz
1940_CCATATGT-ACTGCATA_S864_L007_R1_001.fastq.gz
1940_CCATATGT-AGAGTAGA_S840_L007_R1_001.fastq.gz
1940_CCATATGT-CTAAGCCT_S888_L007_R1_001.fastq.gz
1940_CCATATGT-CTCTCTAT_S816_L007_R1_001.fastq.gz
1940_CCATATGT-GTAAGGAG_S852_L007_R1_001.fastq.gz
1940_CCATATGT-TAGATCGC_S804_L007_R1_001.fastq.gz
1940_CCATATGT-TATCCTCT_S828_L007_R1_001.fastq.gz
1940_CTAGTACG-AAGGAGTA_S884_L007_R1_001.fastq.gz
1940_CTAGTACG-ACTGCATA_S872_L007_R1_001.fastq.gz
1940_CTAGTACG-AGAGTAGA_S848_L007_R1_001.fastq.gz
1940_CTAGTACG-CTCTCTAT_S824_L007_R1_001.fastq.gz
1940_CTAGTACG-GTAAGGAG_S860_L007_R1_001.fastq.gz
1940_CTAGTACG-TAGATCGC_S812_L007_R1_001.fastq.gz
1940_CTAGTACG-TATCCTCT_S836_L007_R1_001.fastq.gz
1940_GAACACTG-AAGGAGTA_S883_L007_R1_001.fastq.gz
1940_GAACACTG-ACTGCATA_S871_L007_R1_001.fastq.gz
1940_GAACACTG-AGAGTAGA_S847_L007_R1_001.fastq.gz
1940_GAACACTG-CTAAGCCT_S895_L007_R1_001.fastq.gz
1940_GAACACTG-CTCTCTAT_S823_L007_R1_001.fastq.gz
1940_GAACACTG-GTAAGGAG_S859_L007_R1_001.fastq.gz
1940_GAACACTG-TAGATCGC_S811_L007_R1_001.fastq.gz
1940_GAACACTG-TATCCTCT_S835_L007_R1_001.fastq.gz
1940_GAGGTGTA-AAGGAGTA_S882_L007_R1_001.fastq.gz
1940_GAGGTGTA-ACTGCATA_S870_L007_R1_001.fastq.gz
1940_GAGGTGTA-AGAGTAGA_S846_L007_R1_001.fastq.gz
1940_GAGGTGTA-CTAAGCCT_S894_L007_R1_001.fastq.gz
1940_GAGGTGTA-CTCTCTAT_S822_L007_R1_001.fastq.gz
1940_GAGGTGTA-GTAAGGAG_S858_L007_R1_001.fastq.gz
1940_GAGGTGTA-TAGATCGC_S810_L007_R1_001.fastq.gz
1940_GAGGTGTA-TATCCTCT_S834_L007_R1_001.fastq.gz
1940_GTAGAGGA-CTAAGCCT_S896_L007_R1_001.fastq.gz
1940_GTGCACAA-AAGGAGTA_S874_L007_R1_001.fastq.gz
1940_GTGCACAA-ACTGCATA_S862_L007_R1_001.fastq.gz
1940_GTGCACAA-AGAGTAGA_S838_L007_R1_001.fastq.gz
1940_GTGCACAA-CTAAGCCT_S886_L007_R1_001.fastq.gz
1940_GTGCACAA-CTCTCTAT_S814_L007_R1_001.fastq.gz
1940_GTGCACAA-GTAAGGAG_S850_L007_R1_001.fastq.gz
1940_GTGCACAA-TAGATCGC_S802_L007_R1_001.fastq.gz
1940_GTGCACAA-TATCCTCT_S826_L007_R1_001.fastq.gz
1940_GTTGAACC-AAGGAGTA_S877_L007_R1_001.fastq.gz
1940_GTTGAACC-ACTGCATA_S865_L007_R1_001.fastq.gz
1940_GTTGAACC-AGAGTAGA_S841_L007_R1_001.fastq.gz
1940_GTTGAACC-CTAAGCCT_S889_L007_R1_001.fastq.gz
1940_GTTGAACC-CTCTCTAT_S817_L007_R1_001.fastq.gz
1940_GTTGAACC-GTAAGGAG_S853_L007_R1_001.fastq.gz
1940_GTTGAACC-TAGATCGC_S805_L007_R1_001.fastq.gz
1940_GTTGAACC-TATCCTCT_S829_L007_R1_001.fastq.gz
1940_GTTGTGGC-AAGGAGTA_S873_L007_R1_001.fastq.gz
1940_GTTGTGGC-ACTGCATA_S861_L007_R1_001.fastq.gz
1940_GTTGTGGC-AGAGTAGA_S837_L007_R1_001.fastq.gz
1940_GTTGTGGC-CTAAGCCT_S885_L007_R1_001.fastq.gz
1940_GTTGTGGC-CTCTCTAT_S813_L007_R1_001.fastq.gz
1940_GTTGTGGC-GTAAGGAG_S849_L007_R1_001.fastq.gz
1940_GTTGTGGC-TAGATCGC_S801_L007_R1_001.fastq.gz
1940_GTTGTGGC-TATCCTCT_S825_L007_R1_001.fastq.gz
1940_TAAGTTCG-AAGGAGTA_S879_L007_R1_001.fastq.gz
1940_TAAGTTCG-ACTGCATA_S867_L007_R1_001.fastq.gz
1940_TAAGTTCG-AGAGTAGA_S843_L007_R1_001.fastq.gz
1940_TAAGTTCG-CTAAGCCT_S891_L007_R1_001.fastq.gz
1940_TAAGTTCG-CTCTCTAT_S819_L007_R1_001.fastq.gz
1940_TAAGTTCG-GTAAGGAG_S855_L007_R1_001.fastq.gz
1940_TAAGTTCG-TAGATCGC_S807_L007_R1_001.fastq.gz
1940_TAAGTTCG-TATCCTCT_S831_L007_R1_001.fastq.gz
)

b= (
474505
B28424
B28445
B22721
B28567
B16078
474504
B28423
VGR_1189
Conacyt_1301
1983
ORT_003
RAY11_023
2099
JCN_046
9346
11319
B5592
95132
11337
B9714
95133
390051
474508
21423
21424
B72152
B28780
B38489
389276
38380
AGM_085
3226
21809
B_26491
B_33430
B16031
08_0807
VGR_1073
B_72236
URRA41_20
DONA1408
B21214
B2157
CPM357
473860
B10698
41775
427264
21748
B39186
21739
427255
19715
B35986
457595
B1176
21372
B67621
427270
B25459
B12875
427269
DOT_20978_rep
B_6223
B19863
B_11778
B_32512
B27826
MISA_068
433910
B_30015
390049
16380
392636
433905
B15102
B12361
3230
3199
B_72212
B_27273
91216
474515
16_129
88482
DOT_20978
DOT_20961
33115
33116
MISA_110
390050
CHIMA_320
B71975
B72245
TXT_27
)

for i in ${a[@]};
for k in ${b[@]};
do mv $i $k;
done

**Comment by VeroIarrachtai** [comment]
Can I see you .csv data? Because I want use a colunm name to create a list of your file names

**Comment by almamelisa** [comment]
Which cvs do you refer?

**Comment by necrosnake91** [comment]
Hi Melisa,

One way to fix your problem is by doing the next:
#Create a list with the names with the old files. You can use a table in a plane format and extract the name of the old files.
```
old_names="take_the_name_of_the_old_names_form_the_.csv"
new_names="take_the_name_of_the_new_names_form_the_.csv"

for i in $old_names; do
mv $i $new_names
done 
```

**Comment by camillethuyentruong** [comment]
for file in *.fastq; do read line;  mv -v "${file}" "${line}";  done < list

**Comment by necrosnake91** [comment]
To store the content in a list with the names of old and the new files run:

```old_names=$(<file.txt)```

**Comment by almamelisa** [comment]
> this command reads the 'list.txt' and parses for each line to rename the files .fastq **in the order that the files are in the folder**
> 
> `for file in *.fastq; do read line; mv -v "${file}" "${line}"; done < list.txt`

This work :)

**Comment by almamelisa** [comment]
> Can I see you .csv data? Because I want use a colunm name to create a list of your file names
With this command you can put in a column everything that is separated by "_", then you can make a dataframe with the vector that only has the barcodes.
`names<-within(data = oldnames, V1<-data.frame 
              (do.call('rbind', strsplit(as.character(V1),"_", fixed = T))))
barcodes<-names$V1$X2
barcodes<-as.data.frame(barcodes)
`

**Comment by almamelisa** [comment]
> The next script worked!
> 
> ```
> old_names=$(<old_names.txt) #Create a list with the name of the old files
> 
> for file in $old_names; do #Change the name of file in the order of old_names
> read line;
> mv -v "${file}" "${line}"; #Change the name of the old files in the same order of the new_names.txt
> done < new_names.txt
> ```

done!! thank you

**Comment by VeroIarrachtai** [comment]
Hi everyone!!!

I got it.
With this command line:
1. You can order your sample names like a seq file (non- human error)
2. This data file is in DATA directory
3. Enjoy the result :)
4. You need accept my pull request and check the file result in DATA directory

```
# Load library

library(tidyr)

# Load data 
data_seq<- read.delim("../DATA/finches_key.txt", header = F)
seq_names<- read.delim("../DATA/oldnames", header = F)

# Make order table
seq_names<- separate(seq_names, V1, c("number", "seq"), 5, remove = TRUE)
seq_names<- separate(seq_names, seq, c("seqs", "info_seq"), 17, remove = TRUE)
seq_names$my_names<- data_seq$V2[match(seq_names$seqs, data_seq$V1)]
order_data <- data.frame(seq_names$seqs, seq_names$my_names)

# Change colnames
names(order_data)<- c("seqs", "my_names")

# Export table
write.table(x= order_data, file = "../DATA/order_data.txt")
```

**Comment by almamelisa** [comment]
Hi Vero, this is the command that I told to separate a column by a regular expression.

With this command you can put in a column everything that is separated by "_", then you can make a dataframe with the vector that only has the barcodes.
names<-within(data = oldnames, V1<-data.frame (do.call('rbind', strsplit(as.character(V1),"_", fixed = T)))) barcodes<-names$V1$X2 barcodes<-as.data.frame(barcodes)

**Comment by almamelisa** [comment]
> Hi everyone!!!
> 
> I got it.
> With this command line:
> 
> 1. You can order your sample names like a seq file (non- human error)
> 2. This data file is in DATA directory
> 3. Enjoy the result :)
> 4. You need accept my pull request and check the file result in DATA directory
> 
> ```
> # Load library
> 
> library(tidyr)
> 
> # Load data 
> data_seq<- read.delim("../DATA/finches_key.txt", header = F)
> seq_names<- read.delim("../DATA/oldnames", header = F)
> 
> # Make order table
> seq_names<- separate(seq_names, V1, c("number", "seq"), 5, remove = TRUE)
> seq_names<- separate(seq_names, seq, c("seqs", "info_seq"), 17, remove = TRUE)
> seq_names$my_names<- data_seq$V2[match(seq_names$seqs, data_seq$V1)]
> order_data <- data.frame(seq_names$seqs, seq_names$my_names)
> 
> # Change colnames
> names(order_data)<- c("seqs", "my_names")
> 
> # Export table
> write.table(x= order_data, file = "../DATA/order_data.txt")
> ```

Thanks :)
