### ISSUE TITLE
READMEs comments

### ISSUE THREAD

**Issue by AliciaMstt** [almamelisa/Euphoniinae-Subfamily#6]
The organization of your project and READMEs is clear, but there are few things that need corrections:

Main README:

* It says "identification of paralogues locus (locus that evolve by speciation and not by duplication)". This is the definition of orthologous loci, not paralogous.

Bin README:
* You need to add the names of the scripts, not only the description of what they do.
* You need to add a short description of what are the rest of the files in BIN, that is: changenames, order_namedata.R, params*.txt and the directory partitionanlyzes

Data README:
You need to describe the files that are/will be in DATA. What enzimes you used for the RADseq? how many samples do you have? what are the files changenames, oldnames, relaxed_besttre.result, strigent_besttree.result?

Meta README:
The pdf with sample information does not indicate which is the name of your samples, therefore there is no way of connecting the metadata to the samples. Please correct this.

General to all: double check your English, you have several grammar and spelling mistakes.

**Comment by almamelisa** [comment]
Hi!

I make your recommendations, for main and bin readme, also  in the data readme I indicate the names of the samples and how identified in the pdf located in Meta directory.

**Comment by AliciaMstt** [comment]
Well done
